name: sentiment_analysis_epp

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.10
  - pip >=21.1
  - setuptools_scm
  - toml

  # Reproducibility
  - conda-lock

  # Package dependencies
  - pytask >=0.2
  - scikit-learn
  - matplotlib>=3.5.1
  - numpy
  - pandas
  - pip
  - python-crfsuite
  # Misc
  - black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda
  - nltk
  # Documentation
  - furo
  - myst-parser
  - nbsphinx

  - pip:
    - -e .
    - sphinxext-opengraph
    - black
